# Generated by Django 6.0.2 on 2026-03-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='langue',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('ar', 'العربية'), ('de', 'Deutsch'), ('es', 'Español'), ('it', 'Italiano')], default='fr', max_length=5),
        ),
    ]
