# Generated by Django 6.0.2 on 2026-02-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_post_image_post_youtube_url_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_url',
            field=models.URLField(blank=True),
        ),
    ]
